### ISSUE TITLE
Do not disburse assets at the destination chain

### ISSUE THREAD

**Issue by DeltaChin** [UltronFoundationDev/chainbridge#66]
**I want to get my assets back and  WARN other users about the risks of using Ultron bridge.**

I have 2 bridge transactions from Ultron to BSC using Ultron bridge.
2 transactions have the same problem: Successfully burned tokens at Ultron chain but not disbursed tokens on BSC side.
Please take the time to solve this. 
Hope Ultron team can fix this error, bring safety to users.

Transactions 1:  https://ulxscan.com/transactions/0x1070c9fd32f7d8df87cc6a26afb569961d02a3c4614dc5c155d4613bf398f336

Transactions 2: https://ulxscan.com/tx/0xf54f12b434fce1fa0ec59412a517647bc8de55245e3013eebdeb79ab82a07277

**Comment by backendultron** [comment]
Hello!
Thanks for letting us know!
We observe that the BSC network seems to have problems starting on Friday when many API services became out of sync from time to time. That causes the situation when some of the bridge transactions become stalled. We are doing our best trying to find the solution for that. At the same time, we are monitoring the networks and detecting these stalled transactions, then re-processing them manually if required.
Please expect all the stalled transactions to be processed on 20.09.2022. The corresponding tx hashes will be posted here.
We're sorry for the inconvenience.

**Comment by softwareultron** [comment]
Hello!
We've just finished processing the stalled transactions. 
Here are tx hashes for your bridge operations:
 - [WBTC](https://bscscan.com/tx/0x25e3c4fd2811e35097ef073dca1351f36ec1846e10d720739d3ae17cfe40f509)
 - [WETH](https://bscscan.com/tx/0x7bb62864e7c744b5a18e684816da0ba77e172dbd1072e7028deb3a43bf0eb541)
 
 Sorry again for the inconvenience.

**Comment by DeltaChin** [comment]
Thank you. I have received my tokens. Hope Ultron team will create a chat group on Discord/Telegram soon. Thank again!
